name: Test
on: # rebuild any PRs and main branch changes
  [pull_request]

jobs:
  deploy: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: ./
        with:
          file: example/clouddeploy.yaml
